require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '**/*.gemspec'
